spring.application.name=ProyectoAplicacionProfesional
spring.thymeleaf.cache=false
server.port=8080
portfolio.admin-email=admin@gianmeza.com
portfolio.storage-path=backed/evidencias
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
