CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    email VARCHAR(190) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    foto_url VARCHAR(500) NOT NULL DEFAULT '/img/mezafoto.jpeg',
    rol ENUM('USUARIO', 'ADMIN') NOT NULL DEFAULT 'USUARIO',
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_usuarios_email (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS semanas (
    id TINYINT UNSIGNED NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    estado ENUM('PROXIMAMENTE', 'COMPLETADA') NOT NULL DEFAULT 'PROXIMAMENTE',
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS trabajos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    semana_id TINYINT UNSIGNED NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(100) NOT NULL,
    contenido LONGBLOB NOT NULL,
    tamano_bytes BIGINT UNSIGNED NOT NULL,
    ruta_publica VARCHAR(500) DEFAULT NULL,
    icono VARCHAR(80) NOT NULL DEFAULT 'bi-file-earmark-arrow-down',
    subido_por BIGINT UNSIGNED DEFAULT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trabajos_semana_nombre (semana_id, nombre_archivo),
    CONSTRAINT fk_trabajos_semana FOREIGN KEY (semana_id) REFERENCES semanas (id) ON DELETE CASCADE,
    CONSTRAINT fk_trabajos_usuario FOREIGN KEY (subido_por) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS enlaces (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    semana_id TINYINT UNSIGNED NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    url VARCHAR(2048) NOT NULL,
    creado_por BIGINT UNSIGNED DEFAULT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_enlaces_semana FOREIGN KEY (semana_id) REFERENCES semanas (id) ON DELETE CASCADE,
    CONSTRAINT fk_enlaces_usuario FOREIGN KEY (creado_por) REFERENCES usuarios (id) ON DELETE SET NULL
) ENGINE=InnoDB;